### ISSUE TITLE
ElvUI unit frames stop working with debounce 1.11

### ISSUE THREAD

**Issue by aaron-j-reeves** [mundi4/Debounce#1]
3x ...ElvUI/Core/Modules/UnitFrames/Elements/FrameGlow.lua:343: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: ElvUF_Player_HealthBarFrameGlow:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@ElvUI/Core/Modules/UnitFrames/Elements/FrameGlow.lua"]:343: in function `FrameGlow_PositionTexture'
[string "@ElvUI/Core/Modules/UnitFrames/Elements/FrameGlow.lua"]:36: in function `func'
[string "@ElvUI_Libraries/Core/oUF/ouf.lua"]:245: in function <ElvUI_Libraries/Core/oUF/ouf.lua:228>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?

Locals:
(*temporary) = ElvUF_Player_HealthBarFrameGlow {
 0 = <userdata>
 PixelSnapDisabled = true
}
(*temporary) = "BOTTOMRIGHT"
(*temporary) = nil
(*temporary) = "BOTTOMRIGHT"

**Comment by aaron-j-reeves** [comment]
If I disable debounce, the unitframes all start working again, no bugstack errors, if I re-enable debounce I get the above bugstack error and none of the elvui unitframes work

**Comment by aaron-j-reeves** [comment]
Sorry, I didnt post all of the error:

3x Debounce/FrameRegistry.lua:159: attempt to index field 'Options' (a nil value)
[string "@Debounce/FrameRegistry.lua"]:159: in function `UpdateRegisteredClicks'
[string "@Debounce/FrameRegistry.lua"]:121: in function `RegisterFrame'
[string "@Debounce/Public.lua"]:29: in function `RegisterFrame'
[string "@DebounceCliqueFake/DebounceCliqueFake.lua"]:12: in function <...aceDebounceCliqueFake/DebounceCliqueFake.lua:8>
[string "@ElvUI_Libraries/Core/oUF/ouf.lua"]:400: in function <ElvUI_Libraries/Core/oUF/ouf.lua:303>
[string "=(tail call)"]: ?
[string "@ElvUI_Libraries/Core/oUF/ouf.lua"]:795: in function `Spawn'
[string "@ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:1109: in function `CreateAndUpdateUF'
[string "@ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:1134: in function `LoadUnits'
[string "@ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:1824: in function `func'
[string "@ElvUI_Libraries/Core/oUF/factory.lua"]:20: in function <ElvUI_Libraries/Core/oUF/factory.lua:16>
[string "=(tail call)"]: ?

Locals:
button = ElvUF_Player {
 GetTargetPingGUID = <function> defined @SharedXML/PingableType.lua:21
 HealthPrediction = <table> {
 }
 unitframeType = "player"
 SetHeight = <function> defined =[C]:-1
 UNIT_ENTERED_VEHICLE = <function> defined @ElvUI_Libraries/Core/oUF/ouf.lua:82
 ResurrectIndicator = Texture {
 }
 CLASSBAR_YOFFSET = 0
 SetAlpha = <function> defined =[C]:-1
 unitEvents = <table> {
 }
 SetWidth = <function> defined =[C]:-1
 SetSize = <function> defined =[C]:-1
 mover = ElvUF_PlayerMover {
 }
 customTexts = <table> {
 }
 __elements = <table> {
 }
 PrivateAuras = ElvUF_Player_PrivateAuras {
 }
 TargetGlow = Frame {
 }
 IsPingable = true
 Portrait3D = PlayerModel {
 }
 Power = ElvUF_Player_PowerBar {
 }
 RaidRoleIndicator = Texture {
 }
 AuraWatch = ElvUF_PlayerAuraWatch {
 }
 FrameGlow = Frame {
 }
 Cutaway = <table> {
 }
 RaisedElementParent = Frame {
 }
 Fader = <table> {
 }
 style = "ElvUF"
 ClassBar = "ClassPower"
 PvPIndicator = Texture {
 }
 PowerPrediction = <table> {
 }
 UNIT_EXITED_VEHICLE = <function> defined @ElvUI_Libraries/Core/oUF/ouf.lua:82
 PvPText = FontString {
 }
 AssistantIndicator = Texture {
 }
 Debuffs = ElvUF_PlayerDebuffs {
 }
 AuraBars = ElvUF_Player_AuraBars {
 }
 AuraHighlight = Texture {
 }
 PixelSnapDisabled = true
 MasterLooterIndicator = Texture {
 }
 RaidTargetIndicator = Texture {
 }
 unit = "player"
 GetContextualPingType = <function> defined @SharedXML/PingableType.lua:17
 AuraHighlightFilterTable = <table> {
 }
 AuraHighlightFilter = true
 AuraHightlightGlow = Frame {
 }
 SHADOW_SPACING = 3
 PartyIndicator = Frame {
 }
 CombatIndicator = Texture {
 }
 ClassBarHolder = Frame {
 }
 RestingIndicator = Texture {
 }
 0 = <userdata>
 RaidRoleFramesAnchor = Frame {
 }
 FocusGlow = Frame {
 }
 LeaderIndicator = Texture {
 }
 BOTTOM_OFFSET = 0
 PLAYER_ENTERING_WORLD = <function> defined @ElvUI_Libraries/Core/oUF/ouf.lua:82
 ThreatIndicator = Frame {
 }
 InfoPanel = ElvUF_Player_InfoPanel {
 }
 Portrait2D = Texture {
 }
 Name = FontString {
 }
 Health = ElvUF_Player_HealthBar {
 }
 ClassPower = ElvUF_Player_ClassBar {
 }
 Buffs = ElvUF_PlayerBuffs {
 }
 Castbar = ElvUF_Player_CastBar {
 }
 MouseGlow = Frame {
 }
}
(*temporary) = nil
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Options' (a nil value)"
DebouncePrivate = <table> {
 RegisterClickQueue = <table> {
 }
 UnitWatch = Frame {
 }
 BuildKeyMap = <function> defined @Debounce/Debounce.lua:135
 BindingInfoToActionMap = <table> {
 }
 Constants = <table> {
 }
 DEBUG = false
 OnSpecialUnitChanged = <function> defined @Debounce/Misc.lua:1289
 CustomStatesUpdaterFrame = DebounceStates {
 }
 RegisterFrame = <function> defined @Debounce/FrameRegistry.lua:47
 UnitWatchHeaders = <table> {
 }
 CleanUpDB = <function> defined @Debounce/Profile.lua:207
 GetUnitWatchHeader = <function> defined @Debounce/UnitWatch.lua:208
 DisplayMessage = <function> defined @Debounce/Misc.lua:1343
 GetBindingIssue = <function> defined @Debounce/Misc.lua:269
 ClickDelegateFrames = <table> {
 }
 UnregisterFrame = <function> defined @Debounce/FrameRegistry.lua:124
 ApplyOptions = <function> defined @Debounce/Misc.lua:1355
 ClearMacroTextCache = <function> defined @Debounce/Misc.lua:970
 GetProfileLayer = <function> defined @Debounce/Profile.lua:203
 GetMouseButtonAndPrefix = <function> defined @Debounce/Misc.lua:157
 dump = <function> defined @Debounce/Constants.lua:171
 ConvertToMacroText = <function> defined @Debounce/Misc.lua:689
 EnumerateProfileLayers = <function> defined @Debounce/Profile.lua:244
 DebounceUI = <table> {
 }
 UpdateBlizzardFrames = <function> defined @Debounce/FrameRegistry.lua:174
 DefaultClickFrame = DebounceClickButton {
 }
 EnableUnitWatch = <function> d

**Comment by mundi4** [comment]
I’m very sorry. I uploaded a temporary fix.
Thank you!!
