### ISSUE TITLE
Pre-Patch

### ISSUE THREAD

**Issue by TheSaltySeagull** [mundi4/Debounce#4]
Pre-Patch is around the corner, and I've tried Debounce on the Beta, and it has been non-functional. Now of course there's always the chance it'll work when 11.0 launches, because Beta is Beta, but I want to inquire if you guys intend to keep this addon updated for the new expansion?

**Comment by mundi4** [comment]
I uploaded temporary fix here [https://github.com/mundi4/Debounce/releases](https://github.com/mundi4/Debounce/releases).

If you find any issue, please let me know.

**Comment by TheSaltySeagull** [comment]
- When loading into the world: https://bit.ly/4bPurko
- When opening Debounce: https://bit.ly/3zSFuMB
- Drag and Drop of spells is non-functional: https://bit.ly/3W8nRzG
- When switching between tabs: https://bit.ly/4fhYkg4 (seems it dropped a spell but is not displaying it correctly. Picture: https://bit.ly/4cU8Jgk)
- Window is not draggable. No error.
- Add...-Button is non-functional. No error.
- Bindings Overview-Button is non-functional. No error.
- Button assignment non-functional. No error.

Quick Video: https://streamable.com/na6bgr

I hope this helps :)

**Comment by mundi4** [comment]
Can you run `/dump GetBuildInfo()` and tell me what game version you are running? I'm not seeing the problems you mentioned, and `GetSpellInfo` is definitely there. I'm on PTR (TWW 11.0). Is there another version of TWW available right now? 

My `/dump GetBuildInfo()` shows:
```
[1]="11.0.0",
[2]="55793",
[3]="Jul 22 2024",
[4]=110000,
[5]="",
[6]=""
```

Meanwhile I'll keep looking into this. Thank you for the help!

**Comment by TheSaltySeagull** [comment]
I can't get into the Game (Beta and PTR) at the moment because of some realm issues, but I'm the real Beta not PTR.
So I can't test it on the PTR. Assuming it works for you on PTR it should work fine.

Beta is this: https://bit.ly/3SkNGv4
PTR is this (same as yours): https://bit.ly/4cQftMt

**Comment by mundi4** [comment]
Can you try [this version](https://github.com/mundi4/Debounce/releases/tag/2.0)? 
I couldn't get into the game, so I couldn't test it.

Beta does not appear on my PC. Apparently, some functions (including `GetSpellInfo`) removed in TWW. The PTR has fallback functions for those removed ones, but Beta doesn't (I think).

**Comment by TheSaltySeagull** [comment]
Servers are down for the near future. PTR and Beta Realms are US-Side and went down for the patch rollout on retail. 

I'll update you once they're up again.

**Comment by TheSaltySeagull** [comment]
Debounce on the Pre-Patch works flawless.

Beta: still can't get into Beta as servers are still down apparently.

**Comment by TheSaltySeagull** [comment]
Found a Bug for retail: When converting a Spell to Macro it loses the Icon of the Spell.

**Comment by mundi4** [comment]
Sorry, the servers aren't up in my region yet. I'll look into it when they're available.

**Comment by TheSaltySeagull** [comment]
New Bug: When placing a spell that is only available to one specialization (e.g., Holy Priest's Smite) into Debounce, the spell is hidden when switching to a specialization that does not have this spell (e.g., Shadow Priest). However, this issue does not occur when converting the spell into a macro.

**Comment by mundi4** [comment]
> New Bug: When placing a spell that is only available to one specialization (e.g., Holy Priest's Smite) into Debounce, the spell is hidden when switching to a specialization that does not have this spell (e.g., Shadow Priest). However, this issue does not occur when converting the spell into a macro.

I'm looking into this. I noticed that Smite changes to Mind Flay when I switch to Shadow, and I think this is the default behavior of the game. I'll keep thinking about whether I should handle this and how to handle it. 

Thanks again for your help!
